### ISSUE TITLE
Completed User Authentication MVP

### ISSUE THREAD

**Issue by sparklerfish** [sparklerfish/purrojects#2]
User auth MVP completed, please review on [purrojects heroku](https://purrojects.herokuapp.com)

**Comment by sparklerfish** [comment]
Hold on, it works locally but not on Heroku.  Please hold off on reviewing :(

**Comment by sparklerfish** [comment]
Update: Working on heroku now! @helenyueyu please feel free to proceed with review/feedback

**Comment by helenyueyu** [comment]
# User Auth

## Functionality

- [X] The main button with logo should link to `/`
- [ ] Has working demo login
- [ ] Smooth, bug free navigation

- **Comment: demo login doesn't work**

### Before Login

- [X] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [X] Errors should display for both `/signup` and `/login`.
- [X] Errors should clear when moving between `/signup` and `/login`.
- [X] Can sign up a user
- [X] Can sign in as a user
- [X] Can log out a user
- [X] Can't sign up with the same username/email
- [X] Pressing enter after filling out the session form should use the form data, not the demo user

- **Comment: no 404 error page**

### After Login

- [X] Should not be able to visit `/login` or `/signup`
- [X] Should be able to refresh the page and still be logged in


## Style

- [X] The site should look exactly like the actual site
- [X] All relevant elements should have `cursor: pointer` on hover
- [X] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production

## Seeds
- [ ] Adequate and appropriate seeds
